### PR TITLE
prevent creating the default table when using a custom entity

### LINKED ISSUE #36: Prevent default craue_config_setting table from being created
Is there a way to prevent the default `craue_config_setting` table from being created when running a `doctrine:migrations:diff`?

I can create a custom entity in my application by doing this: https://github.com/craue/CraueConfigBundle#using-a-custom-entity-for-settings

...however although it produces the `config_setting` custom table, it also includes the `craue_config_setting` table too - which I don't need.

```
$this->addSql('CREATE TABLE config_setting (name VARCHAR(255) NOT NULL, section VARCHAR(255) DEFAULT NULL, value TEXT DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name))');
$this->addSql('CREATE TABLE craue_config_setting (name VARCHAR(255) NOT NULL, section VARCHAR(255) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name))');
```

### PR DESCRIPTION
**Pull request by craue**
An approach to possibly fix #36.

What I don't like is that `BaseSetting.orm.xml` will need to be duplicated (in separated folders due to doctrine/DoctrineBundle#209), so let me know if there's a cleaner way.

### CODE REVIEW

**Comment by crmpicco** [comment]
@craue Thanks for responding so quickly to yesterday's comment on #36 

My Craue Config in `config.yml` looks like this:

```
craue_config:
    entity_name: CRMPiccoBundle\Entity\ConfigSetting
```

and I extend the `BaseSetting` parent class like this:

```
/**
 * ConfigSetting entity for the config_setting table.
 *
 * @author Craig R Morton <crmpicco@aol.com>
 * @date 03-07-2017
 */

namespace CRMPiccoBundle\Entity;

use Craue\ConfigBundle\Entity\BaseSetting;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="Craue\ConfigBundle\Repository\SettingRepository")
 * @ORM\Table(name="config_setting")
 */
class ConfigSetting extends BaseSetting
{
```

This PR looks great to me. It would be great if this was merged in and released to save me maintaining a fork as this bundle does exactly what I need it to do (and more).

Thanks 👍

**Comment by craue** [comment]
I was expecting some more feedback from people actually trying the code about whether it really works as expected and solves the issue.

**Comment by craue** [comment]
Version 2.3.0 is out containing this feature.

**Comment by crmpicco** [comment]
You're a ⭐️ !

**Pull request merged**
