### PR TITLE
add autowiring alias and update instructions for reading/writing settings within a controller

### LINKED ISSUE #49: Service "craue_config" not found
Hi,
I am trying to use this bundle but after following the step for the instalation when I want to retrieve a setting, an error is thrown at this line : `$this->get('craue_config')->get('can_user_participate');`.

The full error I get :

> Service "craue_config" not found: even though it exists in the app's container, the container inside "App\Controller\DefaultController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session" and "twig" services. Try using dependency injection instead.

I am using **Symfony 4.2**

Thanks,
A.

### PR DESCRIPTION
**Pull request by craue**
closes #49

### CODE REVIEW

**Comment by Lennix** [comment]
Is there a specific reason why this wasn't merged yet?

**Comment by craue** [comment]
@Lennix, I hoped for some feedback in #49, that's why. 😏

**Comment by Lennix** [comment]
@craue It works :+1: 
On master (without any special changes to services.yml) I get this error:

> Cannot autowire argument $config of "myAction": it references class "Craue\ConfigBundle\Util\Config" but no such service exists. You should maybe alias this class to the existing "craue_config_default" service.

With this PR it works.

**Comment by craue** [comment]
So let's just merge it...

**Comment by Lennix** [comment]
Thank you.

**Pull request merged**
